### ISSUE TITLE
Crash Report (java.lang.NullPointerException: Ticking block entity)

### ISSUE THREAD

**Issue by Lightone** [TheCBProject/ChickenChunks#1]
when raspawan after die, the game crashed

`at codechicken.chunkloader.tile.TileChunkLoaderBase.func_73660_a(TileChunkLoaderBase.java:161)
    at net.minecraft.world.World.func_72939_s(World.java:1802)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1789)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

[Crash log](http://pastebin.com/i6KRTRrR)

**Comment by covers1624** [comment]
Please test with newer versions, if issue happens again, please open a new issue.
