### ISSUE TITLE
NPE when world unloads

### ISSUE THREAD

**Issue by Shybella** [TheCBProject/ChickenChunks#30]
Forge: 2739
CCL: CodeChickenLib-1.12.2-3.2.0.345-universal
CC: ChickenChunks-1.12.2-2.4.1.71-universal

Steps to reproduce

1. Enable Timeout timer for Chicken Chunks loader to 1. So chunkloader unloads 1 minute after logging out.
2. Place a chunk loader in a custom world (Aroma1997 Mining World or Twilight Forest)
3. Unload that custom world (Nucleus /world unload)
4. Logout and wait for Timer to remove that unloaded chunk

Step 4 is where things fall apart. It's trying to unload a chunk from a unloaded world.

I maybe wrong though. 

Thank you.

```---- Minecraft Crash Report ----

WARNING: coremods are present:
  AstralCore (astralsorcery-1.12.2-1.9.3.jar)
  LibLoader (# LibLoader.jar)
  FMLPlugin (elulib-0.1.12.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.35.jar)
  ForgelinPlugin (Forgelin-1.7.4.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  CoreMod (TickProfiler-1.12-0.0.4.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  SpongeCoremod (spongeforge-1.12.2-2705-7.1.0-BETA-3382.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-84.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 8/20/18 3:28 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at com.google.common.collect.LinkedHashMultimap.create(LinkedHashMultimap.java:122)
	at net.minecraftforge.common.ForgeChunkManager.unforceChunk(ForgeChunkManager.java:857)
	at codechicken.chunkloader.manager.ChunkLoaderManager$TicketManager.remChunk(ChunkLoaderManager.java:112)
	at codechicken.chunkloader.manager.ChunkLoaderManager$ChunkLoaderOrganiser.tickDownUnloads(ChunkLoaderManager.java:381)
	at codechicken.chunkloader.manager.ChunkLoaderManager$PlayerOrganiser.tickDownUnloads(ChunkLoaderManager.java:390)
	at codechicken.chunkloader.manager.OrganiserStorage$SavedData.tickUnloads(OrganiserStorage.java:206)
	at codechicken.chunkloader.manager.ChunkLoaderManager.onTickEnd(ChunkLoaderManager.java:669)
	at codechicken.chunkloader.handler.ChunkLoaderEventHandler.worldTick(ChunkLoaderEventHandler.java:32)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1257_ChunkLoaderEventHandler_worldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:682)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:639)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:273)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:776)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.google.common.collect.LinkedHashMultimap.create(LinkedHashMultimap.java:122)
	at net.minecraftforge.common.ForgeChunkManager.unforceChunk(ForgeChunkManager.java:857)
	at codechicken.chunkloader.manager.ChunkLoaderManager$TicketManager.remChunk(ChunkLoaderManager.java:112)
	at codechicken.chunkloader.manager.ChunkLoaderManager$ChunkLoaderOrganiser.tickDownUnloads(ChunkLoaderManager.java:381)
	at codechicken.chunkloader.manager.ChunkLoaderManager$PlayerOrganiser.tickDownUnloads(ChunkLoaderManager.java:390)
	at codechicken.chunkloader.manager.OrganiserStorage$SavedData.tickUnloads(OrganiserStorage.java:206)
	at codechicken.chunkloader.manager.ChunkLoaderManager.onTickEnd(ChunkLoaderManager.java:669)
	at codechicken.chunkloader.handler.ChunkLoaderEventHandler.worldTick(ChunkLoaderEventHandler.java:32)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1257_ChunkLoaderEventHandler_worldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:682)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:639)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:273)

-- Sponge PhaseTracker --
Details:
	Phase Stack: /**************************************************************************************************************************************************************************************/
/*   - Phase: BlockPhase{}{BlockDropItemsPhaseState}                                                                                                                                  */
/*     Context:                                                                                                                                                                       */
/*     - Source: SpongeBlockSnapshot{worldUniqueId=9a1ac018-146b-4052-a0c4-8c805db4692c, position=(-760, 22, -1193), blockState=minecraft:iron_ore, extendedState=minecraft:iron_ore} */
/*     - CapturedBlocks: CapturedBlocksSupplier{Captured=72}                                                                                                                          */
/*     - CapturedItems: CapturedItemsSupplier{Captured=14}                                                                                                                            */
/*     - CapturedEntities: CapturedEntitiesSupplier{Captured=7}                                                                                                                       */
/*     - CapturedBlockPosition: CaptureBlockPos{pos=null, world=Optional.empty}                                                                                                       */
/**************************************************************************************************************************************************************************************/

Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjj000(MinecraftServer.java:3982)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:889)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:370)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:558)
	at java.lang.Thread.run(Unknown Source)

**Comment by covers1624** [comment]
Seems like another edgecase, how often does this occur?
