### ISSUE TITLE
Chickenchunk not working on server

### ISSUE THREAD

**Issue by Maciejozaman** [TheCBProject/ChickenChunks#40]
Hello,
I try install mod "Chickenchunk" on my server on version 1.12.2. When I start the server, an error pops up:
```java 
"net.minecraftforge.fml.common.MissingModsException: Mod chickenchunks (ChickenChunks) requires [codechickenlib@[3.2.3,)]
[19:16:57] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.common.MissingModsException: Mod chickenchunks (ChickenChunks) requires [codechickenlib@[3.2.3,)]
        at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:266) ~[Loader.class:?]
        at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:572) ~[Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) ~[FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[19:16:57] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: E:\MC_Serwery\Server_z_modami\.\crash-reports\crash-2020-01-10_19.16.57-server.txt"
```

The communicate says that I need: "codechickenlib@[3.2.3,)", but I have installed this mod.
![codechickenlib](https://user-images.githubusercontent.com/56502072/72176668-2b930380-33df-11ea-8615-2169ee6d08dc.png)
Please, help solve this problem, thanks.

**Comment by covers1624** [comment]
Please re-download CCL from one of the official places. http://minecraft.curseforge.com/projects/codechicken-lib-1-8
Do Not download CCL from a mod repost site.
