### ISSUE TITLE
Update check broken

### ISSUE THREAD

**Issue by miiichael** [TheCBProject/ChickenChunks#68]
ChickenChunks 1.16.4-2.7.0.85 reports:
```
[23:53:48] [Forge Version Check/INFO]: [chickenchunks] Starting version check at http://chickenbones.net/Files/notification/version.php?query=forge&file=ChickenChunks&version=1.16.4
[23:53:48] [Forge Version Check/WARN]: Failed to process update information
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.Gson.fromJson(Gson.java:899) ~[gson-2.8.0.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:852) ~[gson-2.8.0.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:801) ~[gson-2.8.0.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:773) ~[gson-2.8.0.jar:?]
        at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:195) ~[forge:?]
        at java.lang.Iterable.forEach(Iterable.java:75) [?:1.8.0_275]
        at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:139) [forge:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385) ~[gson-2.8.0.jar:?]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183) ~[gson-2.8.0.jar:?]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[gson-2.8.0.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?]
        ... 6 more
```

Because:
```
michael@joyola:~$ curl -i 'http://chickenbones.net/Files/notification/version.php?query=forge&file=ChickenChunks&version=1.16.4'
HTTP/1.1 200 OK
Server: nginx/1.19.1
Date: Sun, 28 Mar 2021 15:54:54 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: PHP/7.4.7

<br />
<b>Warning</b>:  count(): Parameter must be an array or an object that implements Countable in <b>/var/www/chickenbones/Files/notification/version.php</b> on line <b>52</b><br />
Err: Unknown mod/versionmichael@joyola:~$ 
```

**Comment by covers1624** [comment]
Already resolved on master, forgot to move ChickenChunks over to the new endpoint.
