### ISSUE TITLE
ConcurrentModificationException crash after server startup

### ISSUE THREAD

**Issue by mcenderdragon** [TheCBProject/ChickenChunks#76]
```
---- Minecraft Crash Report ----
// There are four lights!

Time: 24.08.21 13:15
Description: Exception in server tick loop

java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:1.8.0_251] {}
	at java.util.HashMap$KeyIterator.next(Unknown Source) ~[?:1.8.0_251] {}
	at codechicken.chunkloader.world.Organiser.devive(Organiser.java:130) ~[chickenchunks:1.16.5-2.8.0.86] {re:classloading}
	at codechicken.chunkloader.world.ChunkLoaderHandler.tick(ChunkLoaderHandler.java:243) ~[chickenchunks:1.16.5-2.8.0.86] {re:classloading,pl:capability_inject_definalize:A}
	at codechicken.chunkloader.world.ChunkLoaderHandler.onWorldTick(ChunkLoaderHandler.java:101) ~[chickenchunks:1.16.5-2.8.0.86] {re:classloading,pl:capability_inject_definalize:A}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostWorldTick(BasicEventHooks.java:100) ~[forge:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:857) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:the_bumblezone.mixins.json:entities.MinecraftServerMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.dimension.MixinMinecraftServer_D,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:the_bumblezone.mixins.json:entities.MinecraftServerMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.dimension.MixinMinecraftServer_D,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:the_bumblezone.mixins.json:entities.MinecraftServerMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.dimension.MixinMinecraftServer_D,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:the_bumblezone.mixins.json:entities.MinecraftServerMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.dimension.MixinMinecraftServer_D,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows Server 2019 (amd64) version 10.0
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2494495168 bytes (2378 MB) / 4207738880 bytes (4012 MB) up to 6355222528 bytes (6060 MB)
	CPUs: 12
	JVM Flags: 3 total; -Xms4g -Xmx6g -XX:+UseConcMarkSweepGC
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.32.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.32.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.32.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.32.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.32.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.32
	FML Language Providers: 
		javafml@36.1
		minecraft@1
		kotlinforforge@1.14.0
		scorge@3.1.3
	Mod List: 
		rsrequestify-1.16.3-2.0.1.jar                     |RSRequestify                  |rsrequestify                  |2.0.1               |DONE      |Manifest: NOSIGNATURE
		supermartijn642configlib-1.0.8-mc1.16.jar         |SuperMartijn642's Config Lib  |supermartijn642configlib      |1.0.8               |DONE      |Manifest: NOSIGNATURE
		NetherPortalFix_1.16.3-7.2.1.jar                  |NetherPortalFix               |netherportalfix               |7.2.1               |DONE      |Manifest: NOSIGNATURE
		advancedperipherals-0.6r.jar                      |Advanced Peripherals          |advancedperipherals           |0.6r                |DONE      |Manifest: NOSIGNATURE
		SilentMechanisms-1.16.3-1.0.1+77.jar              |Silent's Mechanisms           |silents_mechanisms            |1.0.1+77            |DONE      |Manifest: NOSIGNATURE
		Industrial Agriculture[Core]-1.16.5-1.8.11.jar    |Industrial Agriculture        |industrialagriculture         |1.16.5-1.8.11       |DONE      |Manifest: NOSIGNATURE
		strawgolem-1.16-1.9.jar                           |Straw Golem                   |strawgolem                    |1.16-1.9            |DONE      |Manifest: NOSIGNATURE
		ChickenDropFeathers-1.0-forge-1.16.5-36.0.0.jar   |ChickenDropFeathers           |chickendropfeathersmod        |1.0                 |DONE      |Manifest: NOSIGNATURE
		sleeping_bags-1.16.5-1.0.1.jar                    |Sleeping Bags                 |sleeping_bags                 |1.16.5-1.0.1        |DONE      |Manifest: NOSIGNATURE
		Neat 1.7-27.jar                                   |Neat                          |neat                          |1.7-27              |DONE      |Manifest: NOSIGNATURE
		IronJetpacks-1.16.5-4.2.1.jar                     |Iron Jetpacks                 |ironjetpacks                  |4.2.1               |DONE      |Manifest: NOSIGNATURE
		ForgeEndertech-1.16.4-7.1.0.0-build.0075.jar      |Forge Endertech               |forgeendertech                |7.1.0.0             |DONE      |Manifest: NOSIGNATURE
		MoreMobGriefingOptions-1.16.5-2.0.1.jar           |More MobGriefing Options      |moremobgriefingoptions        |2.0.1               |DONE      |Manifest: NOSIGNATURE
		CTM-MC1.16.1-1.1.2.6.jar                          |ConnectedTexturesMod          |ctm                           |MC1.16.1-1.1.2.6    |DONE      |Manifest: NOSIGNATURE
		ReAuth-1.16-Forge-3.9.3.jar                       |ReAuth                        |reauth                        |3.9.3               |DONE      |Manifest: 3d:06:1e:e5:da:e2:ff:ae:04:00:be:45:5b:ff:fd:70:65:00:67:0b:33:87:a6:5f:af:20:3c:b6:a1:35:ca:7e
		Placebo-1.16.4-4.5.0.jar                          |Placebo                       |placebo                       |4.5.0               |DONE      |Manifest: NOSIGNATURE
		darkerloadingscreen-2.2.jar                       |Darker Loading Screen         |darkerloadingscreen           |2.2                 |DONE      |Manifest: NOSIGNATURE
		ultimate_unicorn_mod-1.16.5-1.6.1.jar             |Wings, Horns, and Hooves, the |ultimate_unicorn_mod          |1.6.1               |DONE      |Manifest: NOSIGNATURE
		Powah-1.16.5-2.3.16.jar                           |Powah                         |powah                         |2.3.16              |DONE      |Manifest: NOSIGNATURE
		Bookshelf-1.16.5-10.1.11.jar                      |Bookshelf                     |bookshelf                     |10.1.11             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		biomeidfixer-1.16.5-1.0.1.s4.jar                  |Biome Id Fixer by Desagas     |biomeidfixer                  |1.16.5-1.0.1.s4     |DONE      |Manifest: NOSIGNATURE
		Industrial Agriculture[Powah]-1.16.3-1.7.1.jar    |Industrial Agriculture Plugin-|iapp                          |1.16.3-1.7.1        |DONE      |Manifest: NOSIGNATURE
		Apotheosis-1.16.4-4.6.1.jar                       |Apotheosis                    |apotheosis                    |4.6.1               |DONE      |Manifest: NOSIGNATURE
		Morpheus-1.16.5-4.2.70.jar                        |Morpheus                      |morpheus                      |4.2.70              |DONE      |Manifest: NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |DONE      |Manifest: NOSIGNATURE
		TinkersDelight-1.16-1.1.jar                       |Tinker's Delight              |tdelight                      |1.16-1.1            |DONE      |Manifest: NOSIGNATURE
		shetiphiancore-1.16-3.8.5.jar                     |ShetiPhian-Core               |shetiphiancore                |3.8.5               |DONE      |Manifest: NOSIGNATURE
		twilightforest-1.16.5-4.0.490-universal.jar       |The Twilight Forest           |twilightforest                |NONE                |DONE      |Manifest: NOSIGNATURE
		refinedstorage-1.9.13.jar                         |Refined Storage               |refinedstorage                |1.9.13              |DONE      |Manifest: NOSIGNATURE
		Industrial Agriculture[Botania]-1.16.5-1.7.2.jar  |Industrial Agriculture Plugin-|iapb                          |1.16.5-1.7.2        |DONE      |Manifest: NOSIGNATURE
		entangled-1.3.6-mc1.16.5.jar                      |Entangled                     |entangled                     |1.3.6               |DONE      |Manifest: NOSIGNATURE
		endertanks-1.16-1.9.5.jar                         |EnderTanks                    |endertanks                    |1.9.5               |DONE      |Manifest: NOSIGNATURE
		AmbientSounds_v3.1.9_mc1.16.5.jar                 |Ambient Sounds                |ambientsounds                 |3.0.3               |DONE      |Manifest: NOSIGNATURE
		Ping-1.16.4-1.6.9.jar                             |Ping                          |ping                          |1.16.4-1.6.9        |DONE      |Manifest: NOSIGNATURE
		Industrial Agriculture[Silent's Mechanisms]-1.16.5|Industrial Agriculture Plugin-|iapsm                         |1.16.5-1.8.10       |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.16.5-13.1.0.477-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.5-13.1.0.477   |DONE      |Manifest: NOSIGNATURE
		Lollipop-1.16.5-3.2.9.jar                         |Lollipop                      |lollipop                      |3.2.9               |DONE      |Manifest: NOSIGNATURE
		Futurepack-1.16.5-31.2.8465.jar                   |Futurepack                    |futurepack                    |31.2.8465           |DONE      |Manifest: 78:ee:c7:a4:2b:54:18:c6:71:6a:84:82:fa:d9:98:5a:a8:33:83:96:b1:4b:e6:1a:c9:56:58:d7:e8:92:1d:63
		silent-gear-1.16.5-2.6.30.jar                     |Silent Gear                   |silentgear                    |2.6.30              |DONE      |Manifest: NOSIGNATURE
		supermartijn642corelib-1.0.10a-mc1.16.5.jar       |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.10a             |DONE      |Manifest: NOSIGNATURE
		Botania-1.16.5-419.jar                            |Botania                       |botania                       |1.16.5-419          |DONE      |Manifest: NOSIGNATURE
		pamhc2foodextended-1.16.3-1.0.2.jar               |Pam's HarvestCraft 2 Food Exte|pamhc2foodextended            |version             |DONE      |Manifest: NOSIGNATURE
		SolarFluxReborn-1.16.3-16.2.5.jar                 |Solar Flux Reborn             |solarflux                     |16.2.5              |DONE      |Manifest: NOSIGNATURE
		foodpouches-1.16.3-1.0.2.jar                      |Food Pouches                  |foodpouches                   |1.16.3-1.0.2        |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.16.4-53.1.jar                         |Patchouli                     |patchouli                     |1.16.4-53.1         |DONE      |Manifest: NOSIGNATURE
		collective-1.16.5-2.27.jar                        |Collective                    |collective                    |2.27                |DONE      |Manifest: NOSIGNATURE
		ExtraStorage-1.16.5-1.4.1.jar                     |Extra Storage                 |extrastorage                  |1.4.1               |DONE      |Manifest: NOSIGNATURE
		NaturesAura-34.2.jar                              |Nature's Aura                 |naturesaura                   |34.2                |DONE      |Manifest: NOSIGNATURE
		Chargers-1.16.5-3.1.0.5.jar                       |Chargers                      |chargers                      |3.1.0.5             |DONE      |Manifest: 15:a4:a3:0e:d2:f8:64:0c:a4:97:30:5f:48:ba:5f:69:f9:23:42:14:a8:5a:60:3a:b1:b1:29:1a:0a:37:3c:79
		curios-forge-1.16.5-4.0.5.2.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.2      |DONE      |Manifest: NOSIGNATURE
		cc-tweaked-1.16.5-1.97.0.jar                      |CC: Tweaked                   |computercraft                 |1.97.0              |DONE      |Manifest: NOSIGNATURE
		the_bumblezone-1.16.5-2.4.9-forge.jar             |The Bumblezone                |the_bumblezone                |1.16.5-2.4.9-forge  |DONE      |Manifest: NOSIGNATURE
		speedyladders-1.16.5-2.jar                        |Speedy Ladders                |speedyladders                 |1.16.5-2            |DONE      |Manifest: NOSIGNATURE
		CustomStartingGear-1.16.4-2.0.2.1-universal.jar   |Custom Starter Gear           |customstartinggear            |2.0.2.1             |DONE      |Manifest: NOSIGNATURE
		FastLeafDecay-v25.jar                             |FastLeafDecay                 |fastleafdecay                 |v25                 |DONE      |Manifest: NOSIGNATURE
		CodeChickenLib-1.16.5-4.0.2.429-universal.jar     |CodeChicken Lib               |codechickenlib                |4.0.2.429           |DONE      |Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		CBMultipart-1.16.5-3.0.2.119-universal.jar        |CBMultipart                   |cb_multipart                  |3.0.2.119           |DONE      |Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		ProjectRed-1.16.5-4.10.0-beta-44-core.jar         |ProjectRed Core               |projectred-core               |4.10.0-beta-44      |DONE      |Manifest: NOSIGNATURE
		ProjectRed-1.16.5-4.10.0-beta-44-illumination.jar |ProjectRed Illumination       |projectred-illumination       |4.10.0-beta-44      |DONE      |Manifest: NOSIGNATURE
		ProjectRed-1.16.5-4.10.0-beta-44-transmission.jar |ProjectRed Transmission       |projectred-transmission       |4.10.0-beta-44      |DONE      |Manifest: NOSIGNATURE
		ProjectRed-1.16.5-4.10.0-beta-44-exploration.jar  |ProjectRed Exploration        |projectred-exploration        |4.10.0-beta-44      |DONE      |Manifest: NOSIGNATURE
		ProjectRed-1.16.5-4.10.0-beta-44-integration.jar  |ProjectRed Integration        |projectred-integration        |4.10.0-beta-44      |DONE      |Manifest: NOSIGNATURE
		veinmining-forge-1.16.5-0.12.jar                  |Vein Mining                   |veinmining                    |1.16.5-0.12         |DONE      |Manifest: NOSIGNATURE
		BotaniaAdditionsMC1.16.4-1.0.4.jar                |Botania Additions             |botaniaadditions              |1.0.4               |DONE      |Manifest: NOSIGNATURE
		Cucumber-1.16.4-4.1.10.jar                        |Cucumber Library              |cucumber                      |4.1.10              |DONE      |Manifest: NOSIGNATURE
		XPFromHarvest-1.16.3-1.2.1.jar                    |XP From Harvest               |xpfromharvest                 |1.2.1               |DONE      |Manifest: NOSIGNATURE
		pamhc2trees-1.16.3-1.0.1.jar                      |Pam's HarvestCraft 2 Fruit Tre|pamhc2trees                   |1.0.1               |DONE      |Manifest: NOSIGNATURE
		treeharvester_1.16.5-2.5.jar                      |Tree Harvester                |treeharvester                 |2.5                 |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.110.jar                          |Just Enough Items             |jei                           |7.7.1.110           |DONE      |Manifest: NOSIGNATURE
		metalbarrels-3.3a.jar                             |Metal Barrels                 |metalbarrels                  |3.3a                |DONE      |Manifest: NOSIGNATURE
		Craftable Saddle and Horse Armors.jar             |Craftable Saddle Mod          |bkcraftablesaddle             |[1.16,)             |DONE      |Manifest: NOSIGNATURE
		Scannable-MC1.16.5-1.7.3.17.jar                   |Scannable                     |scannable                     |1.7.3.17            |DONE      |Manifest: NOSIGNATURE
		Waystones_1.16.5-7.6.2.jar                        |Waystones                     |waystones                     |7.6.2               |DONE      |Manifest: NOSIGNATURE
		goldenhopper-1.2.0-1.16.3.jar                     |Golden Hopper                 |goldenhopper                  |1.2.0               |DONE      |Manifest: NOSIGNATURE
		journeymap-1.16.5-5.7.1.jar                       |Journeymap                    |journeymap                    |5.7.1               |DONE      |Manifest: NOSIGNATURE
		FruitTrees-1.16.5-2.4.1.jar                       |Fruit Trees                   |fruittrees                    |2.4.1               |DONE      |Manifest: NOSIGNATURE
		Kiwi-1.16.5-3.5.2.jar                             |Kiwi                          |kiwi                          |3.5.2               |DONE      |Manifest: NOSIGNATURE
		BotanyPots-1.16.5-7.0.17.jar                      |BotanyPots                    |botanypots                    |7.0.17              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		BotanyTrees-1.16.5-3.0.5.jar                      |BotanyTrees                   |botanytrees                   |3.0.5               |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		betteranimalsplus-1.16.5-10.2.0.jar               |Better Animals Plus           |betteranimalsplus             |10.2.0              |DONE      |Manifest: NOSIGNATURE
		immersive-portals-0.16-mc1.16.5-forge.jar         |Immersive Portals             |immersive_portals             |0.14                |DONE      |Manifest: NOSIGNATURE
		extradisks-1.16.4-1.5.1.jar                       |Extra Disks                   |extradisks                    |1.5.1               |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.1.32-universal.jar                |Forge                         |forge                         |36.1.32             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Bountiful-1.16.4-3.3.1.jar                        |Bountiful                     |bountiful                     |1.16.4-3.3.1        |DONE      |Manifest: NOSIGNATURE
		inzheFoPCore-v.1.2.0.jar                          |inzheFoPs Core                |inzhefopcore                  |1.0.0               |DONE      |Manifest: NOSIGNATURE
		MysticalAgriculture-1.16.4-4.2.0.jar              |Mystical Agriculture          |mysticalagriculture           |4.2.0               |DONE      |Manifest: NOSIGNATURE
		matc-1.1.2.jar                                    |Mystical Agriculture Tiered Cr|matc                          |1.1.2               |DONE      |Manifest: NOSIGNATURE
		ironchest-1.16.4-11.2.10.jar                      |Iron Chests                   |ironchest                     |1.16.4-11.2.10      |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.1.32-server.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		TConstruct-1.16.5-3.0.4.197.jar                   |Tinkers' Construct            |tconstruct                    |3.0.4.197           |DONE      |Manifest: NOSIGNATURE
		WailaHarvestability-mc1.16.x-forge-1.1.15.jar     |Waila Harvestability          |wailaharvestability           |1.1.15              |DONE      |Manifest: NOSIGNATURE
		nohostilesaroundcampfire_1.16.5-3.4.jar           |No Hostiles Around Campfire   |nohostilesaroundcampfire      |3.4                 |DONE      |Manifest: NOSIGNATURE
		mcpaint-1.6.2.jar                                 |Mc Paint                      |mcpaint                       |1.6.2               |DONE      |Manifest: NOSIGNATURE
		silent-lib-1.16.3-4.9.6.jar                       |Silent Lib                    |silentlib                     |4.9.6               |DONE      |Manifest: NOSIGNATURE
		pamhc2crops-1.16.3-1.0.2.jar                      |Pam's HarvestCraft 2 Crops    |pamhc2crops                   |version             |DONE      |Manifest: NOSIGNATURE
		CreativeCore_v2.2.0_mc1.16.5.jar                  |CreativeCore                  |creativecore                  |2.0.0               |DONE      |Manifest: NOSIGNATURE
		AdLods-1.16.4-4.1.6.1-build.0145.jar              |Large Ore Deposits            |adlods                        |4.1.6.1             |DONE      |Manifest: NOSIGNATURE
		packedup-1.0.23-mc1.16.5.jar                      |PackedUp                      |packedup                      |1.0.23              |DONE      |Manifest: NOSIGNATURE
		ChickenChunks-1.16.5-2.8.0.86-universal.jar       |ChickenChunks                 |chickenchunks                 |2.8.0.86            |DONE      |Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		jeiintegration_1.16.5-7.0.1.15.jar                |JEI Integration               |jeiintegration                |7.0.1.15            |DONE      |Manifest: NOSIGNATURE
		flywheel-1.16-0.1.1.jar                           |Flywheel                      |flywheel                      |1.16-0.1.1          |DONE      |Manifest: NOSIGNATURE
		create-mc1.16.5_v0.3.2b.jar                       |Create                        |create                        |v0.3.2b for 1.16.5  |DONE      |Manifest: NOSIGNATURE
		Mantle-1.16.5-1.6.115.jar                         |Mantle                        |mantle                        |1.6.115             |DONE      |Manifest: NOSIGNATURE
		pamhc2foodcore-1.16.3-1.0.2.jar                   |Pam's HarvestCraft 2 Food Core|pamhc2foodcore                |version             |DONE      |Manifest: NOSIGNATURE
		ftb-backups-2.1.1.6.jar                           |FTB Backups                   |ftbbackups                    |2.1.1.6             |DONE      |Manifest: NOSIGNATURE
		Timber Framing-1.16.4-1.1.0.jar                   |Timber Framing                |timberframing                 |1.1.0               |DONE      |Manifest: NOSIGNATURE
		StorageDrawers-1.16.3-8.2.2.jar                   |Storage Drawers               |storagedrawers                |8.2.2               |DONE      |Manifest: NOSIGNATURE
		enderchests-1.16-1.7.7.jar                        |EnderChests                   |enderchests                   |1.7.7               |DONE      |Manifest: NOSIGNATURE
		HardcoreRevival_1.16.5-5.2.1.jar                  |Hardcore Revival              |hardcorerevival               |5.2.1               |DONE      |Manifest: NOSIGNATURE
		combustivefishing-forge-1.16.3-4.0.0.1.jar        |Combustive Fishing            |combustivefishing             |1.16.3-4.0.0.1      |DONE      |Manifest: NOSIGNATURE
		UltimateSolarPanel-1.16.5-1.4.jar                 |Ultimate Solar Panels         |ultimatesolarpanels           |1.3.0               |DONE      |Manifest: NOSIGNATURE
		Chisel-MC1.16.5-2.0.1-alpha.4.jar                 |Chisel                        |chisel                        |MC1.16.5-2.0.1-alpha|DONE      |Manifest: NOSIGNATURE
		SoL-Carrot-1.16.5-1.10.0.jar                      |Spice of Life: Carrot Edition |solcarrot                     |1.16.5-1.10.0       |DONE      |Manifest: NOSIGNATURE
		Aquaculture-1.16.5-2.1.19.jar                     |Aquaculture 2                 |aquaculture                   |1.16.5-2.1.19       |DONE      |Manifest: NOSIGNATURE
		SilentGems-1.16.3-3.7.16.jar                      |Silent's Gems 3               |silentgems                    |3.7.16              |DONE      |Manifest: NOSIGNATURE
		refinedstorageaddons-0.7.2.jar                    |Refined Storage Addons        |refinedstorageaddons          |0.7.2               |DONE      |Manifest: NOSIGNATURE
		CosmeticArmorReworked-1.16.5-v3a.jar              |CosmeticArmorReworked         |cosmeticarmorreworked         |1.16.5-v3a          |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		chiselsandbits-0.3.4-RELEASE.jar                  |Chisels & bits                |chiselsandbits                |NONE                |DONE      |Manifest: NOSIGNATURE
		healingcampfire_1.16.5-3.3.jar                    |Healing Campfire              |healingcampfire               |3.3                 |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 85a64e0c-eac7-4625-a591-a8312e8124da
	Kiwi Modules: 
		fruittrees:cherry
		fruittrees:core
		fruittrees:hybridization
		kiwi:contributors
		kiwi:data
	Player Count: 2 / 10; [ServerPlayerEntity['Arjuna0284'/427, l='ServerWorld minecraft:overworld FP_Test2', x=1864.99, y=75.00, z=-3131.05], ServerPlayerEntity['MCenderdragon'/727, l='ServerWorld minecraft:overworld FP_Test2', x=-513.33, y=75.00, z=47.15]]
	Data Packs: vanilla, mod:rsrequestify (incompatible), mod:supermartijn642configlib, mod:cucumber, mod:netherportalfix (incompatible), mod:xpfromharvest (incompatible), mod:pamhc2trees (incompatible), mod:treeharvester, mod:jei, mod:bkcraftablesaddle (incompatible), mod:scannable (incompatible), mod:silents_mechanisms (incompatible), mod:chickendropfeathersmod, mod:sleeping_bags, mod:neat (incompatible), mod:ironjetpacks, mod:create, mod:waystones (incompatible), mod:goldenhopper (incompatible), mod:forgeendertech, mod:moremobgriefingoptions, mod:journeymap (incompatible), mod:ctm (incompatible), mod:reauth, mod:fruittrees, mod:kiwi, mod:darkerloadingscreen (incompatible), mod:ultimate_unicorn_mod, mod:betteranimalsplus (incompatible), mod:morpheus (incompatible), mod:waila, mod:immersive_portals (incompatible), mod:extradisks, mod:tdelight, mod:forge, mod:shetiphiancore, mod:inzhefopcore, mod:refinedstorage, mod:mysticalagriculture, mod:matc, mod:ironchest (incompatible), mod:tconstruct, mod:endertanks, mod:ambientsounds, mod:nohostilesaroundcampfire, mod:ping, mod:mcpaint (incompatible), mod:silentlib (incompatible), mod:biomesoplenty, mod:pamhc2crops (incompatible), mod:futurepack, mod:creativecore, mod:adlods, mod:supermartijn642corelib, mod:packedup, mod:chickenchunks (incompatible), mod:pamhc2foodextended (incompatible), mod:jeiintegration, mod:solarflux, mod:foodpouches, mod:mantle (incompatible), mod:pamhc2foodcore (incompatible), mod:ftbbackups (incompatible), mod:collective, mod:timberframing, mod:storagedrawers (incompatible), mod:enderchests, mod:hardcorerevival (incompatible), mod:combustivefishing (incompatible), mod:extrastorage, mod:ultimatesolarpanels, mod:chisel (incompatible), mod:chargers, mod:solcarrot, mod:aquaculture (incompatible), mod:refinedstorageaddons, mod:speedyladders (incompatible), mod:customstartinggear (incompatible), mod:fastleafdecay (incompatible), mod:cosmeticarmorreworked (incompatible), mod:codechickenlib (incompatible), mod:cb_multipart (incompatible), mod:projectred-core (incompatible), mod:projectred-illumination (incompatible), mod:projectred-transmission (incompatible), mod:projectred-exploration (incompatible), mod:projectred-integration (incompatible), mod:veinmining, mod:healingcampfire, mod:wailaharvestability, mod:industrialagriculture, mod:bookshelf, mod:iapb (incompatible), mod:iapsm, mod:botania, mod:patchouli (incompatible), mod:curios, mod:the_bumblezone, mod:botaniaadditions, mod:metalbarrels (incompatible), mod:botanypots, mod:botanytrees, mod:chiselsandbits (incompatible), mod:advancedperipherals, mod:strawgolem, mod:placebo (incompatible), mod:biomeidfixer, mod:apotheosis (incompatible), mod:silentgear, mod:naturesaura (incompatible), mod:computercraft, mod:bountiful (incompatible), mod:silentgems, mod:twilightforest, mod:powah, mod:iapp (incompatible), mod:entangled, mod:lollipop, mod:flywheel
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by covers1624** [comment]
Version `2.9.0.87` has now been released which should resolve this issue.
